project_id = "ynibjnazouypdvwgozih"

[sync-asana-tasks]
verify_jwt = true
max_retries = 3

[send-notification]
verify_jwt = true
max_retries = 3

[schedule-notifications]
verify_jwt = true
max_retries = 3