
project_id = "ynibjnazouypdvwgozih"

[[functions]]
import_map = ["/functions/_shared/import_map.json"]
verify_jwt = true
name = "get-workspace"

[[functions]]
import_map = ["/functions/_shared/import_map.json"]
verify_jwt = true
name = "delete-draft-project"

[[functions]]
import_map = ["/functions/_shared/import_map.json"]
verify_jwt = true
name = "delete-workspace"
